/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later
 * See the lgpl.txt file in the root directory or http://www.gnu.org/licenses/lgpl-2.1.html
 */

apply plugin: 'maven-publish'

// Disable Gradle module metadata publishing until we know what we want.
// https://docs.gradle.org/6.0.1/userguide/publishing_gradle_module_metadata.html#sub:disabling-gmm-publication
tasks.withType(GenerateModuleMetadata) {
	enabled = false
}

def releaseGroup = project.findProperty( 'releaseGroup' ) ?: System.getenv( 'RELEASE_GROUP' )

publishing {
	repositories {
		if ( System.getenv( 'GITHUB_PACKAGES_URL' ) ) {
			maven {
				name = 'GitHubPackages'
				url = uri( System.getenv( 'GITHUB_PACKAGES_URL' ) )
				credentials {
					username = System.getenv( 'GITHUB_ACTOR' )
					password = System.getenv( 'GITHUB_TOKEN' )
				}
			}
		}
	}
	publications {
		publishedArtifacts( MavenPublication ) {
			if ( releaseGroup ) {
				groupId = releaseGroup
			}
			pom {
				name = 'Hibernate ORM - ' + project.name
				description = project.description
				url = 'https://hibernate.org/orm'

				organization {
					name = 'Hibernate.org'
					url = 'https://hibernate.org'
				}

				licenses {
					license {
						name = 'GNU Library General Public License v2.1 or later'
						url = 'https://www.opensource.org/licenses/LGPL-2.1'
						comments = 'See discussion at https://hibernate.org/community/license/ for more details.'
						distribution = 'repo'
					}
				}

				scm {
					url = 'https://github.com/hibernate/hibernate-orm'
					connection = 'scm:git:https://github.com/hibernate/hibernate-orm.git'
					developerConnection = 'scm:git:git@github.com:hibernate/hibernate-orm.git'
				}

				issueManagement {
					system = 'jira'
					url = 'https://hibernate.atlassian.net/browse/HHH'
				}

				developers {
					developer {
						id = 'hibernate-team'
						name = 'The Hibernate Development Team'
						organization = 'Hibernate.org'
						organizationUrl = 'https://hibernate.org'
					}
				}

			}

			if ( releaseGroup ) {
				pom.withXml {
					def ownGroupIds = [ 'org.hibernate.orm', 'org.hibernate.orm.tooling' ] as Set
					def root = asNode()
					def groupIdNodes = root.get( 'groupId' )
					if ( groupIdNodes && ownGroupIds.contains( groupIdNodes[0].text() ) ) {
						groupIdNodes[0].setValue( releaseGroup.toString() )
					}
					root.dependencies.dependency.each { dep ->
						def depGroup = dep.get( 'groupId' )
						if ( depGroup && ownGroupIds.contains( depGroup[0].text() ) ) {
							depGroup[0].setValue( releaseGroup.toString() )
						}
					}
					root.dependencyManagement.dependencies.dependency.each { dep ->
						def depGroup = dep.get( 'groupId' )
						if ( depGroup && ownGroupIds.contains( depGroup[0].text() ) ) {
							depGroup[0].setValue( releaseGroup.toString() )
						}
					}
				}
			}
		}
	}

}
